title: Stefan Pauly
url: "https://stefanpauly.net"
baseurl: ""

github_username:  paustefa

markdown: kramdown

#tracking_id: UA-99337029-1

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
    style: compressed
    sass_dir: _sass
